// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5409.Vimy.subsystems;

import org.usfirst.frc5409.Vimy.commands.*;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.CANError;
import com.revrobotics.CANSparkMax.IdleMode;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Shoulder extends PIDSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private CANSparkMax m_shoulderSlave_SparkMax_C31;
    private CANSparkMax m_shoulderMaster_SparkMax_C30;
    private SpeedControllerGroup shoulder_SparkMaxGroup;
    private AnalogInput s_shoulderAbsoluteEncoder_A0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public double shoulderPositionSensorAngle;

    // Initialize your subsystem here
    public Shoulder() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("Shoulder", 0.03, 0.0, 0.0);
        setAbsoluteTolerance(0.2);
        getPIDController().setContinuous(false);
        getPIDController().setName("Shoulder", "PIDSubsystem Controller");
        LiveWindow.add(getPIDController());
        getPIDController().setOutputRange(-0.15, 0.15);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        m_shoulderSlave_SparkMax_C31 = new CANSparkMax(31, MotorType.kBrushless);
        
        m_shoulderSlave_SparkMax_C31.restoreFactoryDefaults();  
        m_shoulderSlave_SparkMax_C31.setInverted(false);
        m_shoulderSlave_SparkMax_C31.setIdleMode(IdleMode.kCoast);
  
        
        m_shoulderMaster_SparkMax_C30 = new CANSparkMax(30, MotorType.kBrushless);
        
        m_shoulderMaster_SparkMax_C30.restoreFactoryDefaults();  
        m_shoulderMaster_SparkMax_C30.setInverted(false);
        m_shoulderMaster_SparkMax_C30.setIdleMode(IdleMode.kCoast);
  
        
        
        
        //Set SlaveSpeedControllers to Follow MasterSpeedController
        shoulder_SparkMaxGroup = new SpeedControllerGroup(m_shoulderMaster_SparkMax_C30, m_shoulderSlave_SparkMax_C31);
                
                
        
        s_shoulderAbsoluteEncoder_A0 = new AnalogInput(0);
        addChild("s_shoulderAbsoluteEncoder_A0",s_shoulderAbsoluteEncoder_A0);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    
    }
    public void moveShoulder(double angle) {
        setSetpoint(angle);
        enable();
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    @Override
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        
        return shoulderPositionSensorAngle;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    }

    @Override
    public void periodic() {
        shoulderPositionSensorAngle = (s_shoulderAbsoluteEncoder_A0.getVoltage() - 0.5) / 4 * 360 - 90;
        if (shoulderPositionSensorAngle < 0) {
            shoulderPositionSensorAngle += 360;
        }
        SmartDashboard.putNumber("Shoulder Angle", shoulderPositionSensorAngle);
        
    }
    
    
    @Override
    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
        shoulder_SparkMaxGroup.pidWrite(output);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

}
